# Generated by Django 4.1.3 on 2022-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=10)),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
            ],
        ),
    ]
